### ISSUE TITLE
LeastConn using DEAD backends

### ISSUE THREAD

**Issue by tuxmonteiro** [galeb/galeb-libraries#20]

**Comment by igorfernandes** [comment]
Olhando esse final do código, não parece aceitar dead backends, uma vez que quando morto ele sai da lista de uris (assim como random e roundrobin utilizam o uris), ele verifica se existe lá antes de repassar a escolha.. 

int pos = 0;
String choice = backends.poll();
if (choice!=null) {
     pos = uris.indexOf(choice);
}
return pos >= 0 ? pos : 0;

Mesmo com isso, faz sentido filtrar backends apenas que estejam no uris ?

**Comment by igorfernandes** [comment]
Looking at this code, it does not seem to accept a dead backend, since when it dead it leaves the uris list (just like random and round-robin), it checks to see if it exists before passing on a choice:

```
int pos = 0;
String choice = backends.poll();
if (choice!=null) {
    pos = uris.indexOf(choice);
}
return pos >= 0 ? pos : 0;
```

Even with that, does it make sense to filter backends only that are not uris?
